version: '3.8'
services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: spring_batch
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./domain/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - my-network

  api-module-container:
    image: "${DOCKER_USERNAME}/api-module:latest"
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
